### ISSUE TITLE
3.0.0 Update

### ISSUE THREAD

**Issue by IlliaBoloto** [witmul/plutus_backtest#36]
1. Description  to add
2.  Change calling function name
3.  Add separeted Accum return plot in calling function
4.  Create optiona parametr (full report - yes)
5.  Area to fix 
6.  Check plotly express alternatives
7.  Set werkzeug as 2.0.0 
8. Html report to fix 
9. Delete download bottom
10.  Separate plots to different tabs
11.  Accum plot to diversify  
12. Readme
13.  Full check

**Comment by witmul** [comment]
All point were moved to kanban page
